import os
import psycopg2
from dotenv import load_dotenv

# Cargar la URL de tu base de datos desde el archivo .env
load_dotenv()
db_url = os.environ.get("DATABASE_URL")

# El código SQL que creaste, adaptado para que no marque error si lo corres dos veces
sql_crear_tablas = """
-- 1. Crear tabla de Productos
CREATE TABLE IF NOT EXISTS productos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text UNIQUE NOT NULL,
  nombre text NOT NULL,
  categoria text,
  costo numeric NOT NULL,
  precio numeric NOT NULL,
  stock integer NOT NULL,
  unidad text DEFAULT 'pieza'
);

-- 2. Crear tabla de Historial de Ventas
CREATE TABLE IF NOT EXISTS historial (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio_venta text NOT NULL,
  fecha timestamp with time zone DEFAULT timezone('utc'::text, now()),
  descripcion_productos text NOT NULL,
  total numeric NOT NULL,
  vendedor text NOT NULL
);

-- 3. Crear tabla de Usuarios
CREATE TABLE IF NOT EXISTS usuarios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario text UNIQUE NOT NULL,
  nombre text NOT NULL,
  password text NOT NULL,
  rol text NOT NULL
);

-- 4. Insertar datos de prueba (Solo si no existen)
INSERT INTO productos (codigo, nombre, categoria, costo, precio, stock, unidad)
VALUES 
  ('PROD001', 'Laptop Dell 15"', 'Electronica', 8, 12, 10, 'pieza'),
  ('PROD002', 'Mouse Inalámbrico', 'Electronica', 150, 299, 46, 'pieza'),
  ('PROD005', 'Cuaderno Prof.', 'Electronica', 25, 55, 80, 'pieza'),
  ('PROD006', 'PC', 'Electronica', 1500, 2000, 3, 'pieza')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO usuarios (usuario, nombre, password, rol)
VALUES 
  ('admin', 'Lola Lola', 'admin123', 'administrador'),
  ('Emple', 'Erick Santos', 'emple123', 'empleado')
ON CONFLICT (usuario) DO NOTHING;
"""

try:
    print("Conectando a la base de datos en Render...")
    conexion = psycopg2.connect(db_url)
    cursor = conexion.cursor()
    
    print("Creando tablas e insertando datos...")
    cursor.execute(sql_crear_tablas)
    
    # Guardar los cambios
    conexion.commit()
    print("✅ ¡Base de datos configurada exitosamente!")
    
except Exception as e:
    print(f"❌ Error al configurar la base de datos: {e}")
finally:
    if 'cursor' in locals():
        cursor.close()
    if 'conexion' in locals():
        conexion.close()